<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:re="http://www.agenciatributaria.es/respuesta" xmlns:pe="http://www.agenciatributaria.es/peticion"
	targetNamespace="http://www.agenciatributaria.es/ListaEntidades/peticion/wsdl" xmlns:ns="http://www.agenciatributaria.es/ListaEntidades/peticion/wsdl">

	<types>
		<xs:schema targetNamespace="http:/http://www.agenciatributaria.es/datos_wsdl" xmlns:xs="http://www.w3.org/2001/XMLSchema"
			xmlns="http:/http://www.agenciatributaria.es/datos_wsdl">
			<xs:import namespace="http://www.agenciatributaria.es/respuesta" schemaLocation="Respuesta_Lista_Entidades.xsd" />
			<xs:import namespace="http://www.agenciatributaria.es/peticion" schemaLocation="Peticion_Lista_Entidades.xsd" />
		</xs:schema>
	</types>

	<message name="Peticion">
		<part name="Peticion" element="pe:PeticionListaEntidades" />
	</message>

	<message name="Respuesta">
		<part name="Respuesta" element="re:RespuestaListaEntidades" />
	</message>

	<portType name="ListaEntidades">
		<operation name="ListaEntidades">
			<input message="ns:Peticion" />
			<output message="ns:Respuesta" />
		</operation>
	</portType>

	<binding name="ListaEntidades" type="ns:ListaEntidades">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />

		<operation name="ListaEntidades">
			<soap:operation soapAction="urn:#SolicitudTransmisionOper" />

			<input>
				<soap:body use="literal" />
			</input>

			<output>
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>

	<service name="ListaEntidades">
		<port name="ListaEntidades" binding="ns:ListaEntidades">
			<soap:address location="https://www5.aeat.es/L/NCD1NCDLP0DL/" />
		</port>
	</service>
</definitions>